# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLChunk',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.SlugField(verbose_name='Code')),
                ('body_af', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_ar', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_ast', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_az', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_bg', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_be', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_bn', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_br', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_bs', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_ca', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_cs', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_cy', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_da', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_de', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_el', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_en', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_en-au', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_en-gb', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_eo', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_es', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_es-ar', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_es-mx', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_es-ni', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_es-ve', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_et', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_eu', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_fa', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_fi', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_fr', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_fy', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_ga', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_gl', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_he', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_hi', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_hr', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_hu', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_ia', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_id', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_io', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_is', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_it', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_ja', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_ka', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_kk', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_km', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_kn', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_ko', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_lb', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_lt', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_lv', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_mk', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_ml', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_mn', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_mr', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_my', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_nb', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_ne', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_nl', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_nn', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_os', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_pa', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_pl', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_pt', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_pt-br', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_ro', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_ru', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_sk', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_sl', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_sq', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_sr', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_sr-latn', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_sv', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_sw', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_ta', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_te', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_th', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_tr', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_tt', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_udm', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_uk', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_ur', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_vi', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_zh-cn', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_zh-hans', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_zh-hant', models.TextField(default=b'', verbose_name='Body', blank=True)),
                ('body_zh-tw', models.TextField(default=b'', verbose_name='Body', blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
    ]
